// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnQbwRY7i698MPLaiilust1PCNQVxtSS4',
    appId: '1:376171342998:web:31ded9002ef744f03ae6b7',
    messagingSenderId: '376171342998',
    projectId: 'csc450-sp23-project-team-4',
    authDomain: 'csc450-sp23-project-team-4.firebaseapp.com',
    storageBucket: 'csc450-sp23-project-team-4.appspot.com',
    measurementId: 'G-4ZHJPL5RZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8vyLMKUjsEkiUDLuBzR_FC4ld_gwcdb4',
    appId: '1:376171342998:android:7fb0f7570c54ec0d3ae6b7',
    messagingSenderId: '376171342998',
    projectId: 'csc450-sp23-project-team-4',
    storageBucket: 'csc450-sp23-project-team-4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGulVB3pnTrxhKqd6KkshiAFSGJgmRroE',
    appId: '1:376171342998:ios:aecc85b4ecff576f3ae6b7',
    messagingSenderId: '376171342998',
    projectId: 'csc450-sp23-project-team-4',
    storageBucket: 'csc450-sp23-project-team-4.appspot.com',
    iosClientId: '376171342998-i8c9b1g1nri9mghige45osb8cnaihd48.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGulVB3pnTrxhKqd6KkshiAFSGJgmRroE',
    appId: '1:376171342998:ios:aecc85b4ecff576f3ae6b7',
    messagingSenderId: '376171342998',
    projectId: 'csc450-sp23-project-team-4',
    storageBucket: 'csc450-sp23-project-team-4.appspot.com',
    iosClientId: '376171342998-i8c9b1g1nri9mghige45osb8cnaihd48.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
